theme = "rasmus"

[editor]
scrolloff = 0
bufferline = "multiple"
cursorline = true
auto-format = false
rulers = [80]

[editor.cursor-shape]
insert = "bar"

[keys.normal]
C-p = "file_picker"
C-A-j = "extend_line_down"
C-A-k = "extend_line_up"
g = { q = ":reflow" }
C-w = { c = ":buffer-close" }

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-type"]
right = ["diagnostics", "workspace-diagnostics", "selections", "position"]
