theme = "rasmus"

[editor]
scrolloff = 0
bufferline = "multiple"
cursorline = true
auto-format = false
rulers = [80]

[editor.lsp]
display-inlay-hints = true

[editor.soft-wrap]
enable = true
wrap-indicator = "↳ "

[editor.cursor-shape]
insert = "bar"

[keys.normal]
C-p = "file_picker"
X = "extend_line_above"
space = { space = "buffer_picker" }
g = { q = ":reflow" }
C-w = { c = ":buffer-close" }

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-type"]
right = ["version-control", "diagnostics", "workspace-diagnostics", "selections", "position"]

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
newline = "none"
