[[language]]
name = "ruby"
language-servers = [{ name = "solargraph" }]
rulers = [140]

[[language]]
name = "c-sharp"
rulers = []

[[language]]
name = "typescript"
rulers = [120]

[[language]]
name = "markdown"
rulers = []
