env:
  TERM: alacritty

window:
  gtk_theme_variant: dark

font:
  normal:
    family: Source Code Pro

  size: 12

  offset:
   x: 0
   y: 3

# Colors
import:
  - /home/wadii/.config/alacritty/plain.yml

mouse:
  url:
    launcher: firefox
    args: []

key_bindings:
    - { key: F11, action: ToggleFullscreen }
