env:
  TERM: alacritty

shell: fish

window:
  decorations_theme_variant: dark

font:
  normal:
    family: Berkeley Mono

  size: 10.5

  offset:
   x: 0
   y: 0

  glyph_offset:
    x: 0
    y: 0

import:
  - ~/.config/alacritty/ploy.yml

mouse:
  hide_when_typing: true

hints:
  alphabet: "jfkdls;ahgurieowpq"

  enabled:
    - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
              [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      hyperlinks: true
      command: xdg-open
      post_processing: true
      mouse:
        enabled: true
        mods: None
      binding:
        key: O
        mods: Control|Shift

    - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
              [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      hyperlinks: true
      action: Copy
      post_processing: true
      binding:
        key: U
        mods: Control|Shift
