env:
  TERM: alacritty

window:
  gtk_theme_variant: dark

font:
  normal:
    family: mononoki

  size: 12

  offset:
   x: 0
   y: 2

  glyph_offset:
    x: 0
    y: 1

import:
  - ~/.config/alacritty/github_dark.yml

mouse:
  hide_when_typing: true
