env:
  TERM: alacritty

window:
  gtk_theme_variant: dark

font:
  normal:
    family: JetBrains Mono NL

  size: 12

  offset:
   x: 0
   y: 3

import:
  - ~/.config/alacritty/seoul256.yml

key_bindings:
    - { key: F11, action: ToggleFullscreen }
