env:
  TERM: alacritty

window:
  dimensions:
    columns: 90
    lines: 40

  gtk_theme_variant: dark

font:
  normal:
    family: Inconsolata

    style: Regular

  bold:
    style:

  italic:

    style:

  bold_italic:

    style:

  size: 12

  offset:
   x: 0
   y: 3

import:
  - /home/hwadii/.config/alacritty/plain.yml

cursor:
  style: Block

mouse:
  url:
    launcher: firefox
    args: []

key_bindings:
    - { key: F11, action: ToggleFullscreen }
