env:
  TERM: alacritty

window:
  gtk_theme_variant: dark

font:
  normal:
    family: Fira Code

  size: 10.5

  offset:
   x: 0
   y: 0

  glyph_offset:
    x: 0
    y: -1

import:
  - ~/.config/alacritty/zenbones_dark.yml

mouse:
  hide_when_typing: true

hints:
  alphabet: "jfkdls;ahgurieowpq"

  enabled:
    - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
              [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      command: xdg-open
      post_processing: true
      mouse:
        enabled: true
        mods: Shift
      binding:
        key: U
        mods: Control|Shift
