env:
  TERM: alacritty

window:
  gtk_theme_variant: dark

font:
  normal:
    family: Source Code Pro

  size: 12

  offset:
   x: 0
   y: 4

import:
  - ~/.config/alacritty/base16-phd-256.yml

key_bindings:
    - { key: F11, action: ToggleFullscreen }
