shell:
  program: /opt/homebrew/bin/tmux
  args:
    - new-session
    - -ADs
    - x

window:
  decorations_theme_variant: Dark
  option_as_alt: OnlyLeft
  startup_mode: Maximized

font:
  normal:
    family: BerkeleyMono Nerd Font

  size: 15

  offset:
   x: 0
   y: 0

  glyph_offset:
    x: 0
    y: 0

import:
  - ~/.config/alacritty/ploy.yml

mouse:
  hide_when_typing: true

hints:
  enabled:
    - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
              [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      hyperlinks: true
      command: open
      post_processing: true
      mouse:
        enabled: true
        mods: None
      binding:
        key: O
        mods: Control|Shift

    - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
              [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      hyperlinks: true
      action: Copy
      post_processing: true
      binding:
        key: U
        mods: Control|Shift
