env:
  TERM: alacritty

window:
  gtk_theme_variant: dark

font:
  normal:
    family: M+ 1mn

  size: 12

  offset:
   x: 0
   y: 0

  glyph_offset:
    x: 0
    y: 0

import:
  - ~/.config/alacritty/melange.yml
