window:
  dimensions:
    columns: 90
    lines: 40

  gtk_theme_variant: dark

font:
  normal:
    family: Source Code Pro

    style: Regular

  bold:
    style:

  italic:

    style:

  bold_italic:

    style:

  size: 13

  offset:
   x: 0
   y: 3

# Colors (Seoul256)
colors:
  # Default colors
  cursor:
    text: '0x1d1f21'
    cursor: '0xc5c8c6'

  primary:
    background: '#171717'
    foreground: '#d0d0d0'

  # Normal colors
  normal:
    black:   '#4e4e4e'
    red:     '#d68787'
    green:   '#5f865f'
    yellow:  '#d8af5f'
    blue:    '#85add4'
    magenta: '#d7afaf'
    cyan:    '#87afaf'
    white:   '#d0d0d0'

  # Bright colors
  bright:
    black:   '#626262'
    red:     '#d75f87'
    green:   '#87af87'
    yellow:  '#ffd787'
    blue:    '#add4fb'
    magenta: '#ffafaf'
    cyan:    '#87d7d7'
    white:   '#e4e4e4'

cursor:
  style: Block

mouse:
  url:
    launcher: /home/wadii/bin/firefox
    args: []

key_bindings:
    - { key: F11, action: ToggleFullscreen }
