env:
  TERM: alacritty

window:
  gtk_theme_variant: dark

font:
  normal:
    family: Pragmata Pro Mono

  size: 11

  offset:
   x: 0
   y: 4

# Colors
import:
  - /home/wadii/.config/alacritty/base16-tomorrow-night-256.yml

mouse:
  url:
    launcher: firefox
    args: []

key_bindings:
    - { key: F11, action: ToggleFullscreen }
