import = ["~/.config/alacritty/ploy.toml"]
shell = "fish"

[font]
size = 11

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "mono"

[font.offset]
x = 0
y = 0

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
persist = false
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[[hints.enabled]]
action = "Copy"
binding = { key = "U", mods = "Control|Shift" }
persist = false
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[mouse]
hide_when_typing = true

[window]
decorations_theme_variant = "Dark"
