env:
  TERM: alacritty

window:
  gtk_theme_variant: dark

font:
  normal:
    family: Oxygen Mono

  size: 12

  offset:
   x: 0
   y: 1

  glyph_offset:
    x: 0
    y: -2

import:
  - ~/.config/alacritty/github_dark.yml
