env:
  TERM: alacritty

window:
  gtk_theme_variant: dark

font:
  normal:
    family: Julia Mono

  size: 12

  offset:
   x: 0
   y: 3

import:
  - ~/.config/alacritty/seoul256.yml

mouse:
  url:
    launcher: firefox
    args: []

key_bindings:
    - { key: F11, action: ToggleFullscreen }
