colors:
  primary:
    foreground: '#EDE6DE'
    background: '#2A2622'

  cursor:
    text: '#181818'
    cursor: '#d8d8d8'

  normal:
    white:   '#EDE6DE'
    black:   '#38332E'
    red:     '#D65C70'
    yellow:  '#F7C96E'
    green:   '#4DB380'
    cyan:    '#85ADAD'
    blue:    '#9CA7C9'
    magenta: '#997AB8'

  bright:
    white:   '#EDE6DE'
    black:   '#584D41'
    red:     '#F7856E'
    yellow:  '#CC8033'
    green:   '#8BC270'
    cyan:    '#85ADAD'
    blue:    '#9CA7C9'
    magenta: '#D194C7'
