[colors.bright]
black = "#4c4c4b"
blue = "#a6cded"
cyan = "#94c9b2"
green = "#7aae98"
magenta = "#f7b4e1"
red = "#ffafa5"
white = "#eaeaea"
yellow = "#ffdeaa"

[colors.cursor]
cursor = "#dbdbdb"
text = "#1a1a19"

[colors.normal]
black = "#1a1a19"
blue = "#97B2C9"
cyan = "#7bb099"
green = "#61957f"
magenta = "#de9bc8"
red = "#ff968c"
white = "#d1d1d1"
yellow = "#ffc591"

[colors.primary]
background = "#1a1a19"
foreground = "#d1d1d1"
