colors:
  # Default colors
  primary:
    background: '#181a1b'
    foreground: '#d1d1d1'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x061229'
    cursor: '0xb8bbc2'

  # Normal colors
  normal:
    black:   '#4c5356'
    red:     '#c15959'
    green:   '#37ad82'
    yellow:  '#FAC03B'
    blue:    '#5f87af'
    magenta: '#a29bfe'
    cyan:    '#7398dd'
    white:   '#d7d7d7'

  # Bright colors
  bright:
    black:   '0x717885'
    red:     '0xd07346'
    green:   '0x99bf52'
    yellow:  '0xfbd461'
    blue:    '0x5299bf'
    magenta: '0x9989cc'
    cyan:    '0x72b9bf'
    white:   '0xffffff'
