icons = "none"
icons_format = ""

[theme]
name = "native"
[theme.overrides]
separator = ""

[[block]]
block = "focused_window"
max_width = 50
format = "{title} •"

[[block]]
block = "music"
dynamic_width = true
max_width = 1000
marquee = false
format = "{combo} • "
separator = " — "
hide_when_empty = true
on_click = "playerctl play-pause"

[[block]]
block = "battery"
format = "{percentage} {time} •"
full_format = "FULL •"

[[block]]
block = "sound"
on_click = "pavucontrol"
format = "♬ {volume} •"

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total} •"
format_swap = "{swap_used}/{swap_total} •"

[[block]]
block = "net"
device = "wlp2s0"
format = "{ssid} •"
on_click = "gnome-control-center"
interval = 30
hide_missing = true
hide_inactive = true

[[block]]
block = "time"
interval = 60
format = "%a %d %b %H:%M %p"
locale = "fr_FR"
