[theme]
theme = "native"
[icons]
icons = "none"
[icons.overrides]
bat = " | | "
bat_full = " |X| "
bat_charging = " |^| "
bat_discharging = " |v| "
volume_muted = "MUTED"
[theme.overrides]
separator = ""

[[block]]
block = "focused_window"
format = "{$title.str(max_w:50)|} • "

[[block]]
block = "music"
format = "{$combo.str(max_w:1000)|None} • "
[[block.click]]
button = "left"
action = "play_pause"

[[block]]
block = "battery"
format = "$percentage $time • "
full_format = "FULL • "

[[block]]
block = "sound"
format = "$icon $volume •"
show_volume_when_muted = true
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "memory"
format = "$mem_used/$mem_total •"
format_alt = "$swap_used/$swap_total •"

[[block]]
block = "net"
[[block.click]]
button = "left"
cmd = "gnome-control-center"

[[block]]
block = "time"
interval = 60
[block.format]
full = "• $timestamp.datetime(f:'%a %d %b %H:%M %p', l:fr_FR)"
