icons = "awesome5"

[theme]
name = "native"
[theme.overrides]
separator = " "

[[block]]
block = "music"
dynamic_width = true
max_width = 50

[[block]]
block = "battery"
interval = 10
format = "{percentage}"

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "time"
interval = 60
format = "%a %d %b %H:%M %p"
locale = "fr_FR"
