icons = "none"
icons_format = ""

[theme]
name = "native"
[theme.overrides]
separator = ""

[[block]]
block = "focused_window"
max_width = 50
format = "{title} •"

[[block]]
block = "music"
dynamic_width = true
max_width = 1000
marquee = false
format = "{artist} — {title} • "

[[block]]
block = "battery"
format = "{percentage} {time} •"
full_format = "FULL •"

[[block]]
block = "sound"
on_click = "pavucontrol"
format = "♬ {volume} •"

[[block]]
block = "time"
interval = 60
format = "%a %d %b %H:%M %p"
locale = "fr_FR"
