version: 2
root-markers:
  - .git/
  - package.json

provide-definition: true

tools:
  eslint_d: &eslint_d
    lint-command: 'eslint_d -f unix --stdin --stdin-filename ${INPUT}'
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"
    lint-ignore-exit-code: true
    format-command: 'eslint_d --fix-to-stdout --stdin --stdin-filename=${INPUT}'
    format-stdin: true

  prettier: &prettier
    format-command: 'prettier ${--config-precedence:configPrecedence} ${--tab-width:tabWidth} ${--single-quote:singleQuote} ${--trailing-comma:trailingComma}'

languages:
  javascript:
    - <<: *eslint_d
    - <<: *prettier
  typescript:
    - <<: *eslint_d
    - <<: *prettier
  javascript.jsx:
    - <<: *eslint_d
    - <<: *prettier
  javascript.tsx:
    - <<: *eslint_d
    - <<: *prettier
  vue:
    - <<: *eslint_d
    - <<: *prettier
  yaml:
    - <<: *prettier
  json:
    - <<: *prettier
  html:
    - <<: *prettier
  scss:
    - <<: *prettier
  css:
    - <<: *prettier
  markdown:
    - <<: *prettier
